version: '3.8'

services:
  backend:
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      - NODE_ENV=development